### ISSUE TITLE
Alert system for users to see messages

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-frontend#130]
**Is your feature request related to a problem? Please describe.**
Often when a user submits a form, or when the user enters a page that they are not authorized for. You want to show some sort of feedback to the user.

**Describe the solution you'd like**
Create a solution that can be called to show the user a message. Example would be: User is editing a project page, clicks on save, but the backend throws some error and it fails to save. How will the user now? We can let the user know by showing a message bar at the top or with some popover. We could use [alerts](https://getbootstrap.com/docs/4.0/components/alerts/) for this (in Bootstrap) or some other solution like [Alertify](https://alertifyjs.com/examples.html)

**Additional context**
If anyone has any other solutions or recommendations. Comment down below so we can find the  best solution for this project.

**Comment by rubenb994** [comment]
Since we are using ngx-bootstrap I suggest we use their alerts: https://valor-software.com/ngx-bootstrap/#/alerts

**Comment by Brend-Smits** [comment]
> Since we are using ngx-bootstrap I suggest we use their alerts: https://valor-software.com/ngx-bootstrap/#/alerts

Fine by me. Let's stick with NGX Alerts, will be closing this issue. Implementation is depended on the  issue and where user alerts are needed.
