### ISSUE TITLE
Pagination is missing

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-frontend#158]
We do not have any pagination in the frontend. This is not a problem yet, but when we reach a certain amount of projects, the project-overview page will be slow and very large. 

Implement using the ngx-bootstrap pagination module. There is no styling available, so free-style the component using the style guide. 

Refer to: https://api.dex.software/index.html for more information on how to wire up the service to communicate with the API. 

@StijnGroenen , what API call should we make as there is currently no pagination available for the get-all project endpoint?

**Comment by StijnGroenen** [comment]
At the moment, only the search endpoint has pagination support.
Is there a page that shows all projects? In that case, we have two options: Add pagination support to the get all projects endpoint or add support for empty serach queries to the search endpoint.

**Comment by Brend-Smits** [comment]
> At the moment, only the search endpoint has pagination support.
> Is there a page that shows all projects? In that case, we have two options: Add pagination support to the get all projects endpoint or add support for empty serach queries to the search endpoint.

The project overview page: https://dex.software/project/overview shows all the projects at this moment.
I think it might be worth adding pagination support to the get-all projects endpoint. Would this involve a lot of work? If it's too much work, we could use the search query workaround.

**Comment by StijnGroenen** [comment]
This should not be a problem.
I created (and assigned) an new issue for this in the back end repository: https://github.com/DigitalExcellence/dex-backend/issues/156
I also created one for sorting: https://github.com/DigitalExcellence/dex-backend/issues/157

**Comment by Brend-Smits** [comment]
This issue should still be open, the frontend needs to implement the pagination buttons/services. 
Thanks for creating the other issues @StijnGroenen
