### ISSUE TITLE
Footer does not support small screens

### ISSUE THREAD

**Issue by rubenb994** [DigitalExcellence/dex-frontend#163]
**Describe the bug**
The styling of the footer does not support small screens. This results in the footer text displaying very strange.

**To Reproduce**
1. Open DeX frontend
2. Make screen smaller than 768 pixels
3. Footer displays ugly

**Expected behavior**
Footer columns should break up into a smaller amount of columns for smaller screens sizes 
5 cols -> 2 cols -> 1 col

**Screenshots**
![image](https://user-images.githubusercontent.com/34919304/83401690-a8ae2c00-a405-11ea-9698-d4e564f01feb.png)

**Comment by Brend-Smits** [comment]
Related to #114
