### ISSUE TITLE
Make frontend styling uniform

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-frontend#183]
The following styling issues need to be resolved: 

- [x] Contributors on project overview page, fixed in #209 
- [x] Embed button on project overview page needs to be in the same place as the other buttons on that page

**Comment by RensNooren** [comment]
- [ ] Error Message Styling
- [ ] Buttons hover / active states
- [ ] hyperlink (a link) hover / active states (specifically Highlighted projects on homepage)
- [ ] 404 page styling
- [ ] Searchbar styling
- [ ] Project detail page, button placements (such as "highlight project" only when authorized)
- [ ] Contributors on project overview page
- [ ] Accordion styling
- [ ] Pagination page number styling
- [ ] Pagination filter styling
- [ ] Remove background illustration frontpage

**Comment by Brend-Smits** [comment]
> * [ ]  404 page styling
This has a low priority. 
> * [ ]  Project detail page, button placements (such as "highlight project" only when authorized)
What do you mean by this one? I don't think this is related to styling right?

**Comment by Eheijboer** [comment]
for the 404 page, to save time only what is currently on the 404 page needs to be centerd on the page with the footer at te bottom.
