### ISSUE TITLE
Inconsistent naming: "Sign in" and "Login"

### ISSUE THREAD

**Issue by StijnGroenen** [DigitalExcellence/dex-frontend#186]
**Describe the bug**
Not really a bug, but inconsistent naming in the front end. Currently, the front end uses the term "Login" in some places and "Sign in" in others.

**Expected behavior**
Use the same terms everywhere. I suggest using "Sign in" everywhere.

**Screenshots**
![image](https://user-images.githubusercontent.com/8530165/84020167-aeb28880-a982-11ea-95be-b62fd7f26256.png)

**Comment by Brend-Smits** [comment]
Discussed this with @Eheijboer and we should go with "Sign in"

**Comment by rubenb994** [comment]
Yea I definitely agree: see the following article about it: https://github.com/DigitalExcellence/dex-frontend/issues/147
