### ISSUE TITLE
Highlight on frontpage not responsive

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-frontend#195]
**Describe the bug**
When a project name is long, on smaller browser it will go outside its highlight section. 

**To Reproduce**
1. Go to Home page, make sure you have a project highlighted with a long name
2. Scale browser down to mimic small sized windows

**Expected behavior**
Long project names should be cut off and put on the second line

**Screenshots**
https://gyazo.com/e539ae8f6500f8caf7719bf0eca35477

**Additional context**

**Comment by MaxKorlaar** [comment]
This is because of the long placeholder name. It shouldn't happen with multiple words, but this can be fixed anyway just to be certain.
