### ISSUE TITLE
Predictive search queries

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-frontend#196]
**Is your feature request related to a problem? Please describe.**
When searching projects, there is no easy way to find new projects.

**Describe the solution you'd like**
Predictive search queries give the user feedback when typing by predicting that the user might want to look for, a good example is how google does this: 
![image](https://user-images.githubusercontent.com/15904543/90410446-a5dce200-e0aa-11ea-86c9-9f563c0b98a6.png)

This feature would allow users to easily explore possibly new projects.

**Additional context**
Keeping track of performance is very important with this feature.

**Comment by Brend-Smits** [comment]
I will add more information about this issue during the holidays.

**Comment by niraymak** [comment]
Picked up in #403
