### ISSUE TITLE
Banner to show that we're in Beta & "give feedback" button

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-frontend#198]
**Is your feature request related to a problem? Please describe.**
Users are unaware that the release will be beta and that some features may not be implemented yet, we want the user to know and we want them to know where to submit feedback.

**Describe the solution you'd like**
Show a dismissable banner that describes that the current release is beta. Additionally, we should show a button on the bottom right that is not dismissable and shows "Give Feedback" and links to Frontend Github - create new issue page. 

**Additional context**
@Eheijboer was able to make a new design for the banner and the button. The clickable prototype will be updated shortly to reflect these changes.
![image](https://user-images.githubusercontent.com/15904543/84478908-5f29d080-ac92-11ea-896d-32623a50ec0a.png)

**Comment by rubenb994** [comment]
I think we should use the alert service for this beta popup. Maybe it also a good idea to add some kind of beta text next to the logo, which triggers the alert again in case somebody clicked it away and still wants to report an issue

**Comment by Brend-Smits** [comment]
> Maybe it also a good idea to add some kind of beta text next to the logo, which triggers the alert again in case somebody clicked it away and still wants to report an issue @Brend-Smits @Eheijboer what do you guys think about this?

That's okay with me, as long as the design is followed as shown in the image above.

**Comment by rubenb994** [comment]
To which repo issue page should the report issue link refer, the backend or frontend?

**Comment by Brend-Smits** [comment]
>and links to Frontend Github - create new issue page.
dex-frontend
