### ISSUE TITLE
What should we do if there's no highlight?

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-frontend#221]
When there's no highlight to show, we will currently still show this: https://gyazo.com/8305e30f23815211719af58617ca2e5e

Should we hide the entire section?
This will also show an error message saying that there was an error in retrieving the highlighted projects.

**Comment by Eheijboer** [comment]
I would say hide the whole highlight block? or a message saying something like "no highlighted projects yet"
