### ISSUE TITLE
Details page does not show linebreaks in descriptions

### ISSUE THREAD

**Issue by MaxKorlaar** [DigitalExcellence/dex-frontend#230]
Linebreaks are stored in the backend, but the front-end does not display them. By default, browsers ignore newlines in text. This can be overridden with CSS, or you may programatically turn newline characters into line break elements `<br>`.

**Comment by Brend-Smits** [comment]
This should be fixed now on staging, can you verify? @MaxKorlaar

**Comment by MaxKorlaar** [comment]
![image](https://user-images.githubusercontent.com/8917249/85201006-38a40f00-b2fc-11ea-9374-7dbbd860517f.png)

Not currently able to verify this

**Comment by rubenb994** [comment]
This is no longer an issue since we implemented Quill for rich text editing & displaying
![image](https://user-images.githubusercontent.com/34919304/85271362-010fa100-b47b-11ea-942b-f4b6f32ed459.png)
