### ISSUE TITLE
Configure Error handling to not trigger Sentry on 404

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-frontend#231]
**Describe the bug**
Since we are returning 404 in the API when there is nothing to be returned........ Errors are send to Sentry constantly.

**To Reproduce**
1. Go to project-detail page of non-highlighted project
2. Check your console, it will show error 404 highlight not found (that's ok, there is no highlight for this project)
3. Check sentry, error will be logged.

**Expected behavior**
Certain 404's to not be logged in Sentry.

**Screenshots**
https://gyazo.com/aa5ce192347d3dcd9c9de7dee0ad5748

**Comment by StijnGroenen** [comment]
Error code 404 should not be used when there is nothing to return. The 400-499 range of HTTP status codes indicate a client error. When the list of highlights is empty, it is not a client error.
In my opinion, status code 204 (No content) should be used or 200 (OK) with an empty array as the body.

**Comment by Brend-Smits** [comment]
> Error code 404 should not be used when there is nothing to return. The 400-499 range of HTTP status codes indicate a client error. When the list of highlights is empty, it is not a client error.
> In my opinion, status code 204 (No content) should be used or 200 (OK) with an empty array as the body.

Yes please, except we have little time. This should be fixed properly after the initial release. https://github.com/DigitalExcellence/dex-backend/issues/207
