### ISSUE TITLE
Implementing styling fixes 1

### ISSUE THREAD

**Issue by RensNooren** [DigitalExcellence/dex-frontend#233]
A few styling fixes that need to be implemented:

Navigation bar
- [x] Aligning " beta "  logo
- [x] Removing the search bar from the navigation bar

Footer
- [x] Changing the color of the GitHub link to DeX orange
- [x] Aligning the Footer to the bottom to the page (no whitespace on shorter pages)

Home
- [x] Removing the white background from the illustration
- [x] Placeholder of the search bar to " Search Projects "

Search bar
- [x] Removing / replacing the cross icon when searching

Sign in page
- [x] Changing the illustration
- [x] Fixing margin on buttons and text

**Comment by Brend-Smits** [comment]
Some of these issues have already been fixed in #227 but have not yet been deployed
