### ISSUE TITLE
Bug: Error message when opening or editing a project

### ISSUE THREAD

**Issue by StijnGroenen** [DigitalExcellence/dex-frontend#247]
**Describe the bug**
When clicking the edit button on a project or when opening a project page, the UI shows the error message "The project with the identifier could not be found". This is probably happening while the project is still loading.

**To Reproduce**
1. Go to 'A project page'
2. Click on 'The edit button (pencil)'
3. See error message for a split second

**Expected behavior**
Some form of loading message / icon should be displayed.

**Comment by Brend-Smits** [comment]
Ahhhhhhh now I see.... I did not notice this before. 
Nice catch

**Comment by StijnGroenen** [comment]
When you run it locally, it is of course way faster. This makes it much harder to notice.

**Comment by StijnGroenen** [comment]
I just noticed the same problem happening when opening a project page.

**Comment by rubenb994** [comment]
Aah, I am to blame for this, did not think of this scenario. I could display a simple 'Project is being loaded' while the API call is executing. I think the next iteration should implement a nice loading screen.
