### ISSUE TITLE
Bug: Relative links need to be converted

### ISSUE THREAD

**Issue by StijnGroenen** [DigitalExcellence/dex-frontend#250]
**Describe the bug**
When importing a project from GitHub, the markdown readme file is converted to HTML. However, the relative links stay relative. This makes them break.

**Expected behavior**
Relative links should be converted to absolute URLs.

**Comment by rubenb994** [comment]
Do you have an example URL to test this bug with?

**Comment by StijnGroenen** [comment]
> Do you have an example URL to test this bug with?

One of my personal projects has a link to the license file in the readme. GitHub automatically converts the link LICENSE to the actual license file of the current branch. On Dex, the link becomes dex.software/LICENSE since it is relative.

**Comment by rubenb994** [comment]
Could you paste link here so I can use that for testing

**Comment by StijnGroenen** [comment]
The link is just LICENSE (since it is relative).
You could use my project as an example: https://github.com/StijnGroenen/ikea-tradfri-api

**Comment by waltersajtos** [comment]
@RubenFricke I think this is an issue for the backend, not the frontend. Let me know what you think

**Comment by RubenFricke** [comment]
@waltersajtos In the previous example, I can't seem to find a relative link. Do you know if this is still an existing issue?

**Comment by waltersajtos** [comment]
> 
> 
> @waltersajtos In the previous example, I can't seem to find a relative link. Do you know if this is still an existing issue?

Yeah, it's still an issue. If you hover over the link item on github it shows an absolute path but that's some magic on github's end. If you import the project it tries to go to `http://localhost:4200/LICENSE`.

**Comment by RubenFricke** [comment]
Ok thanks, @waltersajtos. I agree an issue on the backend would be more applicable. Thanks for letting me know!
