### ISSUE TITLE
Bug: Unauthorized error

### ISSUE THREAD

**Issue by StijnGroenen** [DigitalExcellence/dex-frontend#253]
**Describe the bug**
When I open a project page I get an alert that says Unauthorized.
The developer console shows that these are for requests to the user endpoint.
I also can't see the edit button for my own projects anymore.
I think that my token might have expired.

**Expected behavior**
No error message

**Screenshots**
![image](https://user-images.githubusercontent.com/8530165/85286572-29a39500-b493-11ea-8493-b822c8698189.png)

**Additional context**
Trace id for the error in the response: |8789e083-4522fac754124989.

**Comment by Brend-Smits** [comment]
Odd, it should silent refresh. WIll take a look later. 
When logging in again, it will fix itself right?

**Comment by StijnGroenen** [comment]
When signing in again it will give one more error, but after that, it works again.

I checked it. My token was indeed expired. The expiry time of the token was only 5 minutes though.

**Comment by StijnGroenen** [comment]
I did some more testing.
I think that the silent refresh stops working when the tab is inactive for a while.

Anyway, even if the token is expired, it should never display this error. It should just sign out the user.

**Comment by rubenb994** [comment]
The  frontend implementation refers to a silent-refresh.html file which is not present in the code base

**Comment by Brend-Smits** [comment]
> The frontend implementation refers to a silent-refresh.html file which is not present in the code base

This is included in the library pretty sure. Rens and I tested this in staging last Thursday.

**Comment by rubenb994** [comment]
Just tested locally on the following url: http://localhost:4200/silent-refresh.html

It gave me a 404 error. So it looks like it is not present. Beside that I see no single reference to this file in the code except the environment. I would expect a reference to it from the angular.json file.

**Comment by Brend-Smits** [comment]
You might be on to something here, I've been trying to find a solution for this. 
Steps to more easily reproduce this locally: 
Replace the IdentityConfig.cs in dex-backend -> Identity Server -> Configuration -> IdentityConfig.cs with the version from this gist: https://gist.github.com/Brend-Smits/9e9a3993722fcdbe57f6716e9076ebc8 

This sets the token life time to 60 seconds and fixes some cors issues. 
I found that changing the frontend URL to /auth-callback works (semi), but results in large amount of requests (kinda logical, this callback is not setup for silent refresh).
