### ISSUE TITLE
Bug: Markdown to HTML wrongly converts underscores to italics

### ISSUE THREAD

**Issue by StijnGroenen** [DigitalExcellence/dex-frontend#255]
**Describe the bug**
Underscores in the readme file of a GitHub project get converted to italics text.

**Expected behavior**
It should keep the underscores in case they existed in the original markdown. It should only convert them to italics if this was the case in the original markdown as well.

**Screenshots**
**Example:**
Before:
![image](https://user-images.githubusercontent.com/8530165/85288761-89e80600-b496-11ea-8bca-306c6b25f94e.png)
After:
![image](https://user-images.githubusercontent.com/8530165/85288716-7341af00-b496-11ea-89e0-e2ec1bc31c4b.png)

**Comment by rubenb994** [comment]
Issue can be fixed with the following config property for showdown: https://github.com/showdownjs/showdown/wiki/Showdown-options#literalmidwordunderscores

**Comment by rubenb994** [comment]
This also means we need to disable the module for Quill which allows us to type markdown in the Quill editor. Should I disable and remove this module?

**Comment by StijnGroenen** [comment]
Mid-word underscores are quite common as text (for technical documentation in readme files). I don't they should be converted to italics. GitHub itself (where we import the readme files from) also does not convert mid-word underscores to italics.

> This also means we need to disable the module for Quill which allows us to type markdown in the Quill editor. Because at the moment it is not configurable. Should I disable and remove this module?

In that case, I think is better to keep the markdown functionality in Quill.

**Comment by rubenb994** [comment]
So you think it would be wise to prioritize markdown typing over proper conversion of markdown? I am really on the fence about this. @Brend-Smits what do you think of this

**Comment by Brend-Smits** [comment]
Markdown typing has priority over de import, the user should check the imported readme file by hand and make modifications if necessary.

**Comment by rubenb994** [comment]
Okay in that case I will not disable the module. I however modified showdown (Markdown convert library) to ignore underscores in words. Meaning that this issue can be closes since we favor Markdown support over conversion.
