### ISSUE TITLE
Project Icon

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-frontend#266]
**Is your feature request related to a problem? Please describe.**
There is no way to add/update the icon of a project

**Describe the solution you'd like**
Add the ability to add/update the icon of a project when creating a project and when updating/editing a project. 

**Additional context**
Discuss with the backend: https://github.com/DigitalExcellence/dex-backend/issues/217

**Comment by waltersajtos** [comment]
Okay so after some discussions with the [backend](https://github.com/DigitalExcellence/dex-backend/issues/217) we are going to implement a generic file-uploader. 

What would be a logical way to implement this?
`<app-file-uploader [acceptMultiple]=false [acceptedTypes]="images/png, images/jpeg, images/jpg"`

And for workflow, if a user DnD's (Drag and Drop)/ selects a file/ image should we instantly upload the file, or do we need an extra button? I think that it would be more user friendly to just upload them.

**Comment by Brend-Smits** [comment]
Workflow that I think is right:
-> User clicks on Project Edit button
-> On the Project Edit page, the user clicks on the project icon button.
-> User can either drag and drop the file in here, or select the file using the file explorer. 
-> Once the file is selected, in the browser we should show like a 'preview', the preview is of course temporary and is only here to let the user know that it's uploaded and to show them how it would look. 
This last step is important, the user wants to see how the selected icon would look, so we need to show a preview somehow, maybe we can show it in base64 temporarily until the user clicks on the 'save project' button.
-> User clicks on the 'save project' icon, project is saved and the image is uploaded to our API using the upload file endpoint. 
-> In case the file upload fails, the user is notified with the reason and is given advice on how to resolve it.

**Comment by StijnGroenen** [comment]
Since uploading an image can take some time, make sure to add a progress bar for the file upload. This makes the user aware of the file upload and hopefully prevents the user from leaving the page / closing the tab.

**Comment by waltersajtos** [comment]
Yeah, I was planning on doing that but I just wasn't sure to instantly start uploading the file so we could display the progress bar per file. I can't think of a way to display the progress on the form submission

**Comment by Brend-Smits** [comment]
A fake progress bar until we get response from the API would be best I think.

**Comment by StijnGroenen** [comment]
It does not necessarily have to be a progress bar. A loading icon would be fine as well. As long as the user knows that the file is still being uploaded.

**Comment by waltersajtos** [comment]
Something like this https://gyazo.com/53b3fd5d9c4fb1fb9cde7de332c7b5fc @Brend-Smits ?

**Comment by Brend-Smits** [comment]
> Something like this [gyazo.com/53b3fd5d9c4fb1fb9cde7de332c7b5fc](https://gyazo.com/53b3fd5d9c4fb1fb9cde7de332c7b5fc) @Brend-Smits ?

I think that's a decent starting point. The design will definitely need some work though.

**Comment by waltersajtos** [comment]
I think I am kind of stuck on this issue till the backend is finished, I will submit a draft pr soon.

**Comment by Brend-Smits** [comment]
> I think I am kind of stuck on this issue till the backend is finished, I will submit a draft pr soon.

@niraymak how far are you with the implementation? Can @waltersajtos pull the branch and start testing it? Can you two work together on this so we don't get stuck?
