### ISSUE TITLE
Update design: Follow Users, Tags/Categories

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-frontend#280]
**Is your feature request related to a problem? Please describe.**
As described in this issue: https://github.com/DigitalExcellence/dex-frontend/issues/270 
We want to have the ability to follow projects, users and categories/tags. There is no design for this yet so we need to figure out where it makes sense to place this feature, how it will look like, if it needs a confirmation modal, etc.

**Describe the solution you'd like**
Updated Adobe XD file. Ensure that this feature is user-tested with people from our target audience. User tests should not take too long as we can't afford to spend weeks designing this.

**Comment by juliaslaats** [comment]
I made some designs, to allow users to be able to follow both users and tags. 

You can see it 'in action' here.
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/71012148/98553564-080b4480-22a0-11eb-8d81-53ecf93d0a34.gif)

And some (more detailed) pictures of the three states of the buttons.

(in order: default, on hover, on clicked)
![image](https://user-images.githubusercontent.com/71012148/98558190-6e469600-22a5-11eb-8175-e9590f71ae4d.png) 

![image](https://user-images.githubusercontent.com/71012148/98558252-80c0cf80-22a5-11eb-98b9-c8c660c90ede.png)

I would love to hear what you think 👍

**Comment by rubenb994** [comment]
I really like the feature, for following people I'm not sure what I think of the alignment of the title and the name of the person to follow. What do you think about this small alignment improvement I made 
![image](https://user-images.githubusercontent.com/34919304/98645689-9e884600-2332-11eb-8af4-4c0754c16bb0.png)

**Comment by Brend-Smits** [comment]
This looks great! However, I'm not sure if I'm a big fan of the colors for the contributors. What do other @DigitalExcellence/frontend think?

**Comment by liekevdvoort** [comment]
I would consider making the labels round in contrast with our button's 
![image](https://user-images.githubusercontent.com/49523639/98648299-63881180-2336-11eb-8968-e34e11c41f38.png)

**Comment by liekevdvoort** [comment]
As for the follow users function what happens when I do that? do I get notifications of his or her projects?

**Comment by liekevdvoort** [comment]
I would maybe make the profiles clickable and then link to their page with their projects with a follow button because I don't think we have space in all the places where we want to display the users to place this. (But make your own mind up about what you want to do with that)

**Comment by juliaslaats** [comment]
@liekevdvoort 
> As for the follow users function what happens when I do that? do I get notifications of his or her projects?

Yes I think that is exactly what would happen, although that was not really part of this issue :D 



> I would maybe make the profiles clickable and then link to their page with their projects with a follow button because I don't think we have space in all the places where we want to display the users to place this. (But make your own mind up about what you want to do with that)

I would like some more people's opinion on that. It could be an option to make it less cluttered. @DigitalExcellence/frontend 

> I would consider making the labels round in contrast with our button's 

I really like that, I'll try that out!

**Comment by juliaslaats** [comment]
I made a second version, yay! 

![image](https://user-images.githubusercontent.com/71012148/98660127-3bec7580-2345-11eb-9adb-1522a75ba387.png)


I made the tags more round, I agree this looks a lot better!
![image](https://user-images.githubusercontent.com/71012148/98659977-06478c80-2345-11eb-85bb-8433122d0dae.png)

I made the contributors a different color, and added a better alignment.
![image](https://user-images.githubusercontent.com/71012148/98660328-7a823000-2345-11eb-95fa-fdf634918375.png)

But since I felt like it got very stretched out with this new alignment (especially when looking at it in the full page view)
I also made this option: 
![image](https://user-images.githubusercontent.com/71012148/98659928-f62fad00-2344-11eb-9089-23d0c9beb689.png)

An other idea is that the roles would only pop-up if you hover over someone's name, I would like to know if that's a good option I should try out in a design.

Thanks for the feedback so far, I'd love to hear what you think of this 👍

**Comment by liekevdvoort** [comment]
Yeah i like the hover idea i'm thinking maybe you could put the title in a tooltip and just get rid of the follow tooltip because if you keep the hovers like this you still need to put margins on top when it's not hovered otherwise everything will move

**Comment by juliaslaats** [comment]
I think for the role to display on hover, it would work best with the first contributor option. If the role I on the same line as the name, like in the first option, the name would just slide to the right, there'll probably just be room for that.

But I can also try out as a tooltip, thankyou!

**Comment by Brend-Smits** [comment]
Is this finished?

**Comment by RubenFricke** [comment]
@liekevdvoort @macfleury-2000 Could you take a look into this and tell me the status of this issue? Thanks!

**Comment by niraymak** [comment]
This is the final design.
