### ISSUE TITLE
Update design: Like a project

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-frontend#281]
**Is your feature request related to a problem? Please describe.**
As described in #270, we want to have the ability to like projects. There is no design for this yet so we need to figure out where it makes sense to place this feature, how it will look like and if it needs things like a confirmation modal, etc. 

**Describe the solution you'd like**
Updated Adobe XD file. Ensure that this feature is user-tested with people from our target audience. User tests should not take too long as we can't afford to spend weeks designing this.

**Comment by liekevdvoort** [comment]
Can we close this one?

**Comment by juliaslaats** [comment]
I think so, @Brend-Smits ?
