### ISSUE TITLE
Create robots.txt to guide webcrawlers

### ISSUE THREAD

**Issue by Niekvandam** [DigitalExcellence/dex-frontend#284]
The robots.txt file is used to deny or allow certain web crawlers on parts of the website. This restriction can be used to increase our rankings by SERPs (Search Engine Result Pages), and can disallow unknown web crawlers as long as they abide the robots.txt

However, when Googlebot needs to crawl a lot of dynamically generated pages, it will take longer to index the entire webpage, which could negatively affect the index rating. A good explanation is offered by this [blog post](https://neilpatel.com/blog/robots-txt/)

**Comment by Brend-Smits** [comment]
This is closed in https://github.com/DigitalExcellence/dex-frontend/pull/295 right?
