### ISSUE TITLE
Implement google analytics

### ISSUE THREAD

**Issue by Niekvandam** [DigitalExcellence/dex-frontend#293]
Implement google analytics on the website and update the privacy policy accordingly

**Comment by StijnGroenen** [comment]
I am not sure updating the privacy policy will be enough. I think you also explicitly need to ask the user for consent.

**Comment by Brend-Smits** [comment]
Yes Stijn is right. I need to discuss this with our dataofficer

**Comment by Brend-Smits** [comment]
We need a good use case before we can implement this. I will close it until we have one.
