### ISSUE TITLE
Implement update highlight

### ISSUE THREAD

**Issue by niraymak** [DigitalExcellence/dex-frontend#294]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to update a highlight.

**Describe the solution you'd like**
An option on the project details page to update existing highlights (if you have the right credentials).

**Additional context**

**Comment by Brend-Smits** [comment]
Will need a new "Edit Highlight" button. The edit highlight modal will need to show a list view of the available highlights. Then the user selects a highlight they want to edit and click on "Continue", new modal should then open up that will allow the user to edit the actual description and time of the highlight. This modal should be identical to the existing 'create highlight' modal, except filled in with information.
