### ISSUE TITLE
Create user friendly urls for webpages

### ISSUE THREAD

**Issue by Niekvandam** [DigitalExcellence/dex-frontend#298]
At the moment there are non-SEO friendly urls in the project. For example `/project/details/21` should be something along the lines of `/project/details/name-of-project` . This means that we have to remove the robotic urls which work with ID's and make it readable to our visitors as well. 

This way the googleBot and other crawlers can rank our pages higher in the SERPs and would in theory result in accumulating more traffic.

**Comment by Brend-Smits** [comment]
Sounds good, I think the URL should be like this:
/project/details/PROJECTIDHERE-PROJECTNAME
example: /project/details/1-this-is-my-project-name
