### ISSUE TITLE
Pagination query parameters are not cleared on new search

### ISSUE THREAD

**Issue by matir8** [DigitalExcellence/dex-frontend#302]
**Describe the bug**
Currently, we can only search for projects only on the selected page. For example, when you go to the second page of the projects list and you enter a search the results will be shown only for projects on the second page. We want to search through all the projects. So we should clear the pagination query parameters when making a new search.

**To Reproduce**
1. Search for a project on the first page
2. Make sure that it appears in the results
3. Clear the search query
4. Go to the second page
5. Execute the same search
6. Now the project that was found on the first page is missing

**Expected behavior**
When searching for a project the results should not be limited only to the current page. Pagination query parameters should be cleared on every new search.

**Comment by Brend-Smits** [comment]
Nice find :)
