### ISSUE TITLE
Edit project buttons not working after redirect

### ISSUE THREAD

**Issue by waltersajtos** [DigitalExcellence/dex-frontend#314]
**Describe the bug**

**To Reproduce**
1. Go to a project-detail page
2. Click on the edit button
3. Edit the project
4. Click save
5. The edit and delete button don't work anymore

**Expected behavior**
The buttons to be clickable after a redirect

**Additional context**
I'm not sure why it's not working, the URLs seem to be there on the buttons but they are not clickable.

**Comment by waltersajtos** [comment]
It seems like this is caused by the alert, it closes but it is somehow blocking the buttons

**Comment by Brend-Smits** [comment]
Closed in favor of #352
