### ISSUE TITLE
Design: Project Wizard

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-frontend#319]
**Is your feature request related to a problem? Please describe.**
There is currently a very poor implementation of the project-add page. It's messy and is not user friendly.

**Describe the solution you'd like**
We want to add a so-called Wizard that guides users through the process of adding a project or idea. This needs to take into account that we want to add deeper integration with sources like Gitlab, Github, CodePen, Canvas (this deeper integration includes users having to log in, and being able to select an entry to import using an access token). Previous semester we already started working on some designs for this, but weren't able to finish them.

**Additional context**
Work together on this large issue. Update the Adobe XD designs and post screenshots down below when this issue is finished. Regularly check with me to see if it's aligned with stakeholders' interests.

**Comment by DaveyHurkmans** [comment]
Started making some Designs for this AdobeXD

<img width="791" alt="designs-wizard" src="https://user-images.githubusercontent.com/31689204/97155312-77981480-1775-11eb-9460-9a5c2dd0ca1e.png">

**Comment by Brend-Smits** [comment]
I think we should take a look at a few examples and see what we like about these examples. 
https://dribbble.com/shots/4411666-MonkeyLearn-Wizard-Part-2
The thing I like about this one is the 'source selection' at the start. I think we could benefit from something like that as well. We could essentially make the whole project-add page into a wizard. Thoughts? I also like that the header on the page (the blue text saying Preview - Setup), is a nice addition. 

https://dribbble.com/shots/3813658-Insure-Landing
Looking at this example I quite like the smooth animations. It really walks you through everything and doesn't feel like you are entering different pages or states. With our current design, the user will have to continuously click next for instance, this might get annoying at times. 

I like the way you're thinking Davey, the design looks nice with the stepper. However, I think we should broaden our view.
Let's start with the way we want to shape this wizard, please let me know what you think of this format:
- First step is to ask what they want to add, an idea, or a project? (in the future we could add more options like an internship assignment or things)
- Step 2 could be dynamic based on what they selected in step 1. If they selected a project we may want to ask them if the project can be imported from a third-party application like Canvas, Github, Gitlab, CodePen (these are our sources). If they selected "idea" in step 1, I don't think we need to ask this? Perhaps we could simply have a button with "no, this can't be imported"
- Step 3 is also dependent on what they selected in option 2, but it might be nessecary for them to authenticate with a third-party application like Canvas or Github for us to be able to retrieve the information with their token.
- Step 4 is the step where we showcase what information we were able to automatically retrieve (maybe?)
- Step 5 is where we ask the user to enter the remaining information like the tags or something that we are not able to retrieve as it's custom to our system. This is also the place where we could guide them through on adding images or other content to their submission
- Step 6 is a summary of their project, this will showcase the information that is entered and allows the user to review it and make changes if necessary. 
- Step 7 is where the user has clicked submit and where we can thank them for adding a project. This could also be the place for a button to take them to their project, to share the project on different media's or to submit another submission. 

These steps that I described above are subject to change and should probably be worked out in a more detailed storyboard or something. Only when you have a good idea of what steps are required, you are able to make a truly amazing wizard. At least, that's what I think. What are your thoughts on these ideas and is this something you can work with? I'm always able to provide more feedback. 
Also curious what the rest of @DigitalExcellence/frontend thinks about this and if they have any ideas or designs they like (let us know why as well!). 

Keep up the good work 👍🏼

**Comment by liekevdvoort** [comment]
I think we maybe should consider making it more like an edit inside of the end result (for the project that don't get auto loaded or after they are loaded to adjust) so you can kind of preview how it looks once it's on dex for users to see.

Don't know if that's a clear explanation

![image](https://user-images.githubusercontent.com/49523639/97161987-d9a94780-177e-11eb-85fc-cde372feaa7c.png)

**Comment by juliaslaats** [comment]
I like your design Davey, I think it could be a bit more 'fun'. Maybe some icons or graphics would help, I know a lot of people don't like to read, so that would help with that as well.

I think the steps Brend put in order would be good. It will also help to give a bit more 'flow' to the steps. Step 6 is similar to what Lieke points out, I think. So that would be a good addition. It would be nice if that same editing-environment could be accessed trough an 'edit' button if you are the owner of a project.

**Comment by DaveyHurkmans** [comment]
My idea was to implement Dex Rex to help with the wizard like clippy would do in the old ms word

**Comment by DaveyHurkmans** [comment]
**Wizard overview page design:**
![wizard-overview](https://user-images.githubusercontent.com/31689204/98166243-696d9500-1ee7-11eb-9d29-5073a653f089.jpg)

**Wizard design**
![wizard](https://user-images.githubusercontent.com/31689204/98166247-6a062b80-1ee7-11eb-9df1-a3683097e686.jpg)

**Comment by liekevdvoort** [comment]
For the overview, I would try making the background white and the inputs grey or white with a shadow. I think the layout looks good.

For the wizzard I would place different images for each step, (you probably already wanted to do this)

**Comment by juliaslaats** [comment]
It looks really good! I like that it's both clean and functional, but still fun (especially with the future addition of the DeX Rex) 👍 

I do have a couple remarks/questions: 
- of the screens in your first image, I like the bottom-left one the most, but I don't know if it's a choice between those?
- What will the Add project overview page be used for? I still think that looks a bit too cluttered. 
- How will the wizard be displayed? Because right now it looks to be too square to be full screen, does that mean it will be a pop-up? Or will it have the header and footer added too it? That might give it a bit less of a minimalistic feel. Maybe you could try out how that looks, if needed?
- And one last minor thing: maybe the bottom of the button could be aligned with the bottom of the input-field, because it's hovering a little weirdly now in my opinion.

**Comment by liekevdvoort** [comment]
Maybe this is a informed choice but I don't know if I would make the progress bar stop halfway between the points

**Comment by DaveyHurkmans** [comment]
Two new versions with other images, thanks for the feedback guys!

![image](https://user-images.githubusercontent.com/31689204/98535959-3fb9c280-2287-11eb-9879-945a364224da.png)
![image](https://user-images.githubusercontent.com/31689204/98535334-33813580-2286-11eb-8fdd-531c53a550df.png)

**Comment by DaveyHurkmans** [comment]
Added step 5 and 6, @Brend-Smits Could we brainstorm about what content we need. I made these six but I dont know if I missed something!
![image](https://user-images.githubusercontent.com/31689204/98538483-1bf87b80-228b-11eb-8768-4668753b0fde.png)

**Comment by DaveyHurkmans** [comment]
> * of the screens in your first image, I like the bottom-left one the most, but I don't know if it's a choice between those?
**Both are options, i didnt know if we wanted to categorize them or just loose options.**

> * What will the Add project overview page be used for? I still think that looks a bit too cluttered.
**Editing after the wizard and checking if everything is correct, any ideas to make it less cluttered maybe remove the orange boxes?**

> * How will the wizard be displayed? Because right now it looks to be too square to be full screen, does that mean it will be a pop-up? Or will it have the header and footer added too it? That might give it a bit less of a minimalistic feel. Maybe you could try out how that looks, if needed?
**They will be displayed over the Overview page and while filling in the wizard they will add content to the overview page**

> * And one last minor thing: maybe the bottom of the button could be aligned with the bottom of the input-field, because it's hovering a little weirdly now in my opinion.
**I now made it so that there are 2 places either after the input line (if page has only one small add line) and on the right side (_see last image_)**

**Comment by juliaslaats** [comment]
@DaveyHurkmans 
> Both are options, i didnt know if we wanted to categorize them or just loose options.

In that case my opinion stays the same, I'd prefer the bottom-left one!

> Editing after the wizard and checking if everything is correct, any ideas to make it less cluttered maybe remove the orange boxes?

Would it be an option to make the layout more similar to the existing project page?

So it would look something like this, but maybe with edit-buttons added for quick editing? 
<img src="https://user-images.githubusercontent.com/71012148/98560331-f332af00-22a7-11eb-8051-6b7355703915.png" width="750" />

> They will be displayed over the Overview page and while filling in the wizard they will add content to the overview page

Alright, I think that would look alright.

> I now made it so that there are 2 places either after the input line (if page has only one small add line) and on the right side (see last image)

Looking great!

I like the new designs, I do think the option with the people would be more fitting for DeX than the one with the little monsters, although I do like that one more personally :) 

It also might be nice to add a close (or cancel) button, for if people want to stop at any point.

**Comment by DaveyHurkmans** [comment]
I named the the text of the button "Finish" on the last page, I might copy the design of off liekes new designs for the project pages :)

**Comment by Brend-Smits** [comment]
This looks amazing! Let's schedule a meeting for today @DaveyHurkmans to discuss and brainstorm them? Does anyone else want to join?

**Comment by liekevdvoort** [comment]
could you make a version with the progress steps horizontal it seems a bit full in the middle and leftover space at the top and bottom this would also make it better responsive for mobile. Not sure if it will work well but it seems that the space is there

**Comment by liekevdvoort** [comment]
Wanted to add think it looks good !

**Comment by DaveyHurkmans** [comment]
@liekevdvoort changed the colors like you asked!
![image](https://user-images.githubusercontent.com/31689204/98798978-ccdb5380-240e-11eb-80a8-28e7ffac38b7.png)

**Comment by liekevdvoort** [comment]
Yes since the wizard isn't in a popup you can take both options (ik weet niet hoe je dit in het engels zegt "wat mij betreft) choose which one you like most

**Comment by DaveyHurkmans** [comment]
yes thought I might give it a go :) to reply to youre proposal :D

**Comment by DaveyHurkmans** [comment]
Updated the wizard designs to include the project icons and project images:
![image](https://user-images.githubusercontent.com/31689204/98928465-1b095900-24da-11eb-8723-5dff9ddc68e4.png)

I will still have to take a look at:
- Different flows per source
- Screens for authorisation / source (Was thinking an iframe that directs to the login page / @juliaslaats @liekevdvoort )

**Comment by liekevdvoort** [comment]
@Brend-Smits @DaveyHurkmans moeten we nog nadenken over de verschillende tabs die in de popup komen en of hier nog extra inputs in moeten daarvoor?

**Comment by liekevdvoort** [comment]
En we moeten het nog hebben over de categorieen en project icon als losse dingen voordat we dit de project detail en de overview gaan bouwen

**Comment by Brend-Smits** [comment]
> En we moeten het nog hebben over de categorieen en project icon als losse dingen voordat we dit de project detail en de overview gaan bouwen
> 
> En misschien ook nog over de mobiele designs en wat er gebeurt als je in de popup op edit klikt kom je dan in een overview of in de project builder hierboven

I don't speak Dutch :( Can you edit your message and translate it to English please so everyone can join in on the conversation? Thanks!

**Comment by liekevdvoort** [comment]
@Brend-Smits yes sorry I forgot

**Comment by DaveyHurkmans** [comment]
Some first iterations for the mobile version:

![image](https://user-images.githubusercontent.com/31689204/99958221-46692f00-2d89-11eb-9964-16e6e0ba4854.png)

**Comment by Brend-Smits** [comment]
Perfect, we can move onto implementation now. Nice work everyone, thanks for the extensive feedback! 
#361 is the issue for the implementation part.

**Comment by Brend-Smits** [comment]
To give some more insights on previous concerns:
- The tabs that are shown in #323 for instance, can easily be added to the wizard by adding new steps. The image gallery step that is currently shown, can go into their own step. The same goes for any other information that would be required in the future. An example would be the "technical" tab.
- Categories are not currently implemented in the backend, and thus should not be shown in production for the time being. This does not mean that we should stop designing for it or stop developing tags/categories in the frontend. In fact, the current development branch has always had tags implemented, just static and hidden in production. We do the same now. 
- If you want to edit a project after you submitted a project, you will not go back to the project wizard. Instead, you should be using an edited version of the project detail page.
- Project icons will be shown if the project has one. If the project does not have an icon, a placeholder icon should be shown. It's no different than our current implementation.
