### ISSUE TITLE
Design & Implementation: Updated Background

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-frontend#320]
**Is your feature request related to a problem? Please describe.**
Background is currently very plain and boring.

**Describe the solution you'd like**
Interest the design a bit more by implementing a clean and nicer background. A very subtle icon or color shift might be enough.

**Additional context**
Davey and Julia already started working on this.

**Comment by DaveyHurkmans** [comment]
![image](https://user-images.githubusercontent.com/31689204/97286969-4fc3b200-1844-11eb-80c1-0aa8c1e867fc.png)
Design session #1 with julia

**Comment by DaveyHurkmans** [comment]
@Brend-Smits Feedback please

**Comment by juliaslaats** [comment]
To prevent weird scaling of the background we thought of the option to make it fixed. That way the background always has a similar size, so it won't look weird when the page gets longer. As you can see we made a couple different options, all with he same idea of putting the logo in the background to make it a bit more visually appealing. 

We can show the designs more dynamically in the meeting with @DigitalExcellence/frontend this afternoon, but any feedback right now is welcome!

**Comment by DaveyHurkmans** [comment]
![dex-background-fix](https://user-images.githubusercontent.com/31689204/98117198-a9ae2280-1ea9-11eb-83aa-21c683c89c97.gif)

**Comment by juliaslaats** [comment]
I finetuned the sizing of the background, it now looks like this:

![gif-background](https://user-images.githubusercontent.com/71012148/98120365-26db9680-1eae-11eb-8bc3-3dd21331fb02.gif)
