### ISSUE TITLE
Design & Implementation: Smooth Animations

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-frontend#321]
**Is your feature request related to a problem? Please describe.**
DeX can feel a little bit shallow and plain. 

**Describe the solution you'd like**
Adding miscellaneous things like animations on clicking a button, hovering something or a loading screen will give DeX users a better feeling. These animations need to be consistent and should not draw away the attention of users. 

**Additional context**
Update both the designs (if possible), and code for this.

**Comment by juliaslaats** [comment]
I made a start on adding some animations to DeX to make it look a little more exciting.  I don't feel like I'm done yet, but I would love some feedback about what I've made so far. It's on [this branch](https://github.com/DigitalExcellence/dex-frontend/tree/feature/321-smooth-animations).

What I've added:

**On homepage**
- Spinning animation search button
- Search bar grows when typing in it
- Scaling on hightlight cards
- Lift-up of 'Give Feedback' button

**On overview**
- spinning animation search button

**On login**
- Scaling of login buttons

**Extra thing I did**
I noticed that the phone on the svg on the login page was still in a colour that wasn't visible on the background, so I changed that to a darker color. 

@DigitalExcellence/frontend @Brend-Smits @DaveyHurkmans

**Comment by liekevdvoort** [comment]
Why do you use ease in and not ease-in-out

Maybe it's an idea to put the transitions and scale's etc in the variables stylesheet so they stay the same everywhere (you can still make an exception)

Looking great!

**Comment by juliaslaats** [comment]
> Why do you use ease in and not ease-in-out

I didn't really think about it, ease-in-out is probably better

> Maybe it's an idea to put the transitions and scale's etc in the variables stylesheet so they stay the same everywhere (you can still make an exception)

That's smart, I'll do that :)

> Looking great!

Thankyou! thanks for the feedback!

**Comment by Brend-Smits** [comment]
GIFs would speed up the review process. I will be able to check out this branch later hopefully to actually review it in person, but pictures, videos, or gifs would have allowed me to already comment on it ^^

**Comment by juliaslaats** [comment]
I changed my transitions and transformations to have variables. And here's some gifs for quick reviewing :)

![ezgif-4-cbcc1aa303b8](https://user-images.githubusercontent.com/71012148/101149456-40900b00-361f-11eb-808d-32b6a37caf81.gif)
![ezgif-4-67c848b14a8c](https://user-images.githubusercontent.com/71012148/101149624-7cc36b80-361f-11eb-892c-b834a5ed816c.gif)
![ezgif-4-77d5dd1d509f](https://user-images.githubusercontent.com/71012148/101149751-a7152900-361f-11eb-91e7-0c14241a6877.gif)
![ezgif-4-1512defe51a6](https://user-images.githubusercontent.com/71012148/101150057-07a46600-3620-11eb-8dc7-90a7089362a9.gif)

**Comment by juliaslaats** [comment]
Put some animations on the (new) project overview page:

![ezgif-4-b724194cb43d](https://user-images.githubusercontent.com/71012148/101328755-bb9c3000-3870-11eb-8cc2-93b51833e9ff.gif)
![ezgif-4-ea656e19dfb0](https://user-images.githubusercontent.com/71012148/101328833-d79fd180-3870-11eb-9c58-8682d92dd41e.gif)

![ezgif-4-953339a87c9a](https://user-images.githubusercontent.com/71012148/101329220-66145300-3871-11eb-92eb-c76b0d4968c5.gif) ![ezgif-4-0acf0b365487](https://user-images.githubusercontent.com/71012148/101329159-4ed56580-3871-11eb-8d93-5f4bf2432a9f.gif)

**Comment by devoncavis** [comment]
Is there a reason why the login buttons scale the opposite way of the other hovers? Making them grow would be more consistent with the rest of the button hovers.

Also this is a minor detail (and probably down to personal preference), but especially the spinning search icon feels a little slow to me. I think a little more speed would make it feel more 'ready to go' if that makes sense.

Either way this looks great! The animations definitely make it feel more alive and interactive.

**Comment by juliaslaats** [comment]
@devoncavis the difference basically has to do with the fact that there's less room for growing at the login-buttons. But I agree it would be better to have it consistent. I'll look at it again, also at the speed for the animations, thanks for the feedback!
