### ISSUE TITLE
Redesign: Project Detail Page

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-frontend#323]
**Is your feature request related to a problem? Please describe.**
The project detail page needs a solution for the many buttons, and maybe a more interesting page layout.

**Describe the solution you'd like**
A redesign to make the project detail page more interesting, while keeping it clean and organized. The redesign should also take into consideration that we will be expanding into adding more content on these pages like image galleries (for project showcases), tabs like "technical information" or "contact information".

The design needs to be created for multiple resolutions (mobile/desktop/tablet)

**Comment by liekevdvoort** [comment]
![image](https://user-images.githubusercontent.com/49523639/97293796-70dcd080-184d-11eb-8a2a-903bc3409f03.png)
![image](https://user-images.githubusercontent.com/49523639/97293849-8225dd00-184d-11eb-9a86-52fad91c9973.png)

Voordelen popup
- sneller in klikken minder van een commitment
- makkelijker responsive
- context blijft op de achtergrond
- visueel wit werkt beter op de achtergrond denk ik
- meer icoontjes
- zelfde inhoud compacter (hierdoor willen mensen het waarschijnlijk sneller lezen)
- zorgt ervoor dat de regels om te lezen niet te breed worden zonder gekke witruimtes rechts

Eventueel labels rond maken in contrast met een knop

**Comment by liekevdvoort** [comment]
![project-details-with-image](https://user-images.githubusercontent.com/49523639/97703339-c1079d00-1ab0-11eb-8a81-4f05bdbb077c.PNG)
![project-details-with-image-small](https://user-images.githubusercontent.com/49523639/97703343-c1a03380-1ab0-11eb-8e12-21f3d4e9e901.PNG)
![project-details-without-image](https://user-images.githubusercontent.com/49523639/97703345-c1a03380-1ab0-11eb-9d83-538b2da97644.PNG)
![project-details-without-image-small](https://user-images.githubusercontent.com/49523639/97703347-c238ca00-1ab0-11eb-9f87-4b93795c7475.PNG)

**Comment by liekevdvoort** [comment]
Keep in mind that these popups are normally not visible but i wanted to include them to show how it works. It would be a lot less messy when these are not opened but they normally are not

**Comment by juliaslaats** [comment]
I think they look really good. If I'm being picky, it feels a bit odd to me to put that all the way outside of the popup window (especially on the desktop view). Would it be an option to put that in the corner of the little window?

**Comment by Brend-Smits** [comment]
I think the designs look great, awesome work. I think we should also include the modal popups from editing/adding/removing a highlight in the designs to make them complete. Could this be added?

**Comment by liekevdvoort** [comment]
![image](https://user-images.githubusercontent.com/49523639/98399579-e8d3a380-2062-11eb-92f2-9c336cd567e7.png)
![image](https://user-images.githubusercontent.com/49523639/98399641-00ab2780-2063-11eb-8169-94402d5b8f65.png)
Design highlight popups with structure how it is now

![image](https://user-images.githubusercontent.com/49523639/98399702-1caec900-2063-11eb-9352-e2a665b9b86b.png)
Design test everything in one popup. This popup isn't ready but just an experiment if this one is preferred in way of working to the other one I'll finish it.

**Comment by Brend-Smits** [comment]
@matir8 what do you think of the above designs?

**Comment by Brend-Smits** [comment]
As discussed, I think we should move forward using the following designs:
https://user-images.githubusercontent.com/49523639/98401299-bd9e8380-2065-11eb-9399-e483418b8b86.png
https://user-images.githubusercontent.com/49523639/98399641-00ab2780-2063-11eb-8169-94402d5b8f65.png

Once the mobile versions are ready, we can move onto implementation.

**Comment by liekevdvoort** [comment]
(mobile) designs new hightlight settings popup @Brend-Smits 
![image](https://user-images.githubusercontent.com/49523639/98653625-8964e480-233d-11eb-856f-f0d2a427cd9b.png)
![image](https://user-images.githubusercontent.com/49523639/98653659-9550a680-233d-11eb-8e9e-84789108a73b.png)
![image](https://user-images.githubusercontent.com/49523639/98653696-a3062c00-233d-11eb-91ec-2c1e17f73fe4.png)
![image](https://user-images.githubusercontent.com/49523639/98653725-adc0c100-233d-11eb-8917-bbdbc8f65bf3.png)

**Comment by liekevdvoort** [comment]
When there is no highlight the project details popup says create highlights and links you directly to the second popup 

if there are more highlights the project details popup will say highlight settings and link to the first popup if you click on one of the items you go to the specif highlights settings

**Comment by liekevdvoort** [comment]
I'm not too great with text so if you find more fitting names for the highlight popup's title just adjust them to your liking

**Comment by liekevdvoort** [comment]
![image](https://user-images.githubusercontent.com/49523639/98654326-77d00c80-233e-11eb-9b8e-891f7293feea.png)
![image](https://user-images.githubusercontent.com/49523639/98654354-81597480-233e-11eb-982a-39768b4ef706.png)


![image](https://user-images.githubusercontent.com/49523639/98654417-93d3ae00-233e-11eb-8f7e-6629f9069954.png)
![image](https://user-images.githubusercontent.com/49523639/98654502-b239a980-233e-11eb-97e5-6f9c285cf4e6.png)

**Comment by liekevdvoort** [comment]
Totaal overview
![image](https://user-images.githubusercontent.com/49523639/98655817-33de0700-2340-11eb-94f3-6b41cb5836e4.png)

**Comment by juliaslaats** [comment]
![image](https://user-images.githubusercontent.com/71012148/99951509-85de4e00-2d7e-11eb-9b73-61e571f1c768.png)

I made a design to combine this with my designs from #280 , like discussed before. 

Would like to know what you think @liekevdvoort @DaveyHurkmans

**Comment by liekevdvoort** [comment]
Yes nice, I would keep the contributors with a number in the top part of the popup if you want without the tooltip because it's relevant info I think.

**Comment by DaveyHurkmans** [comment]
@juliaslaats did we not agree upon using the 1 color contributor cards? I think we spoke about it in the first design meeting a couple of weeks ago. Can you upload the different design options so we could vote on them? :)

**Comment by liekevdvoort** [comment]
![image](https://user-images.githubusercontent.com/49523639/100082076-0e74f100-2e48-11eb-8ec5-4a74288ee86c.png)

**Comment by juliaslaats** [comment]
Updated according to yesterdays feedback:
![image](https://user-images.githubusercontent.com/71012148/100084429-0d918e80-2e4b-11eb-8256-f35880a1d671.png)

I did notice that due to me using Liekes design, a couple icons didn't work in my Xd because (of course) Adobe couldn't find them on my laptop. For some reason they turned into words. Maybe it'll look better if Lieke opens it locally, I'll put my Xd files in the drive either way. 

Also this last update that @liekevdvoort just posted is not yet in the version I made. Keep that in mind when looking at it 😇

As a response to @DaveyHurkmans 
> @juliaslaats did we not agree upon using the 1 color contributor cards? I think we spoke about it in the first design meeting a couple of weeks ago. Can you upload the different design options so we could vote on them? :)

I don't think we need to vote. I agree that just one color looks way better.

**Comment by juliaslaats** [comment]
Also feeback for @liekevdvoort I think it looks really good! 

Maybe the buttons on the bottom could be centered a little better. And will they always be visible, or only when the 'description' tag is open?

If they're always open, maybe there can be a little divider between them and the description.

**Comment by liekevdvoort** [comment]
@juliaslaats only in the description and people can turn them on so they most likely won't be visible all at the same time
