### ISSUE TITLE
Research: Streamlining the design process

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-frontend#328]
**Is your feature request related to a problem? Please describe.**
Currently we have to share the Adobe XD files manually after each change. This does not work properly and is very annoying.

**Describe the solution you'd like**
Research how we can streamline this process so everyone can work together and we don't have to upload adobe xd files manually.

**Comment by waltersajtos** [comment]
Adobe offers a paid plan that integrates this into the xD itself, I never used it but people say it works good. It's 10$ per month, that might be an issue
https://www.adobe.com/products/xd/pricing/individual.html?promoid=4F569MBS&mv=other
