### ISSUE TITLE
Design & HTML: Design a DeX mail template

### ISSUE THREAD

**Issue by niraymak** [DigitalExcellence/dex-frontend#341]
**Is your feature request related to a problem? Please describe.**
With upcoming notification system I think it is required to have template for mails. 

**Describe the solution you'd like**
Design and HTML page functioning as a template for mailing.

**Additional context**

**Comment by Brend-Smits** [comment]
Do we have dex mail templates now? @Ruby77

**Comment by Ruby77** [comment]
Basically the same issue as #417  @Brend-Smits

**Comment by Brend-Smits** [comment]
Nice, looking forward to seeing those.
