### ISSUE TITLE
Fix layout on project detail page for small devices

### ISSUE THREAD

**Issue by juliaslaats** [DigitalExcellence/dex-frontend#348]
**Describe the bug**
On small devices, the layout of the project detail website doesn't work well. 

**To Reproduce**
1. Open dex.software on smaller (mobile) devic
2. Click on project to go project detail place
3. See error

**Screenshots**

<img src="https://user-images.githubusercontent.com/71012148/98525640-05e1bf80-2279-11eb-940a-5778fd55b7b2.png" width="300" />

**Suggested fix**
Don't display the icon on smaller devices

**Production URL**
You can see the problem here on the project detail page: https://dex.software/project/details/3-Digital-Excellence

**Comment by liekevdvoort** [comment]
Can we close this one since were implementing the new design?

**Comment by Brend-Smits** [comment]
> Can we close this one since were implementing the new design?

Definitely, thanks!
