### ISSUE TITLE
Unclickable 'edit' / 'delete' project icons

### ISSUE THREAD

**Issue by niraymak** [DigitalExcellence/dex-frontend#352]
**Describe the bug**
Sometimes it is not possible to click the 'edit' / 'delete' project icon in the project details page.
It is still unclear what causes this problem.

**To Reproduce**
1. Go to https://dex.software/project/add/source
2. Login with your FHICT account.
3. Upload a project.
4. Redirect to your uploaded project.
5. Hover / click over edit / delete buttons (shown in image below).

**Expected behavior**
If you are the owner of a certain project it should be possible to click on the edit / delete project icons on the project details page.

**Screenshots**
Not visible in the image, but edit and delete project icons (in the top right of the image) are not clickable
![image](https://user-images.githubusercontent.com/44868678/98696540-365a5400-2374-11eb-902c-4af5e9bc9bf6.png)

**Additional context**
It seems like refreshing using CTRL + F5 fixes the problem.
In mobile view I also seem to be able to click the image. It might have something to do with the notification banner being in front of the icons.

![image](https://user-images.githubusercontent.com/44868678/98697650-7110bc00-2375-11eb-8497-7b4a9e5aeca2.png)
![image](https://user-images.githubusercontent.com/44868678/98697657-740bac80-2375-11eb-82ef-d56d10efa26c.png)

**Comment by Brend-Smits** [comment]
Thanks for the bug report, please also check out #314 for some additional details.
