### ISSUE TITLE
Collaborator name length

### ISSUE THREAD

**Issue by niraymak** [DigitalExcellence/dex-frontend#354]
**Describe the bug**
When the collaborator's name is too long the delete icon's don't show up properly and the names overlap the other ones.

**To Reproduce**
1. Upload projects
2. Add collaborators with longs names

**Expected behavior**
The names don't overlap each other and the delete icon's show up like the other ones.

**Screenshots**
https://gyazo.com/50dec2a9d454cc3bae782cbf6ed7a59b

**Additional **
Maybe should give field collaborator name a maximum length.

**Comment by Yuqera** [comment]
This bug will only be fixed at Add Project since the other locations of this bug have already been fixed.
