### ISSUE TITLE
Implementation: Project Wizard

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-frontend#361]
**Is your feature request related to a problem? Please describe.**
Outdated project-add page.

**Describe the solution you'd like**
Implement the designs from #319 

**Additional context**
Davey is taking lead on implementation.

**Comment by waltersajtos** [comment]
I think we need to create a flow for every source before we start implementing anything so we are sure that the implementation makes sense.

**Comment by Brend-Smits** [comment]
> I think we need to create a flow for every source before we start implementing anything so we are sure that the implementation makes sense.

The available steps/designs are sufficient for all the flows we could think of at this moment. Davey will take on the majority of the development as he knows the ins and outs.

**Comment by DaveyHurkmans** [comment]
I have started working on the prototype designs, there is still some work to do the next things still have to be done:

- Implement a stepper on the side
- Step 3 and 4 of the wizard
- Mobile responsiveness improvement
- Have the forms in the wizard send the data to the "add project overview" page
- Backend implementation 

Add project:
![image](https://user-images.githubusercontent.com/31689204/101785967-aa1b8800-3afd-11eb-9da0-6e6e29a017de.png)

Add project overview: (zoomed out)
![image](https://user-images.githubusercontent.com/31689204/101786137-e0f19e00-3afd-11eb-91d8-7fa7453c5493.png)

Wizard / Project name:
![image](https://user-images.githubusercontent.com/31689204/101786243-fe266c80-3afd-11eb-81f7-5d4dd3d7a84b.png)

Wizard / Describe a project:
![image](https://user-images.githubusercontent.com/31689204/101786578-61180380-3afe-11eb-988d-fcef32715d42.png)

Wizard / Collaborators:
![image](https://user-images.githubusercontent.com/31689204/101786724-8c025780-3afe-11eb-9cfe-f79f6381de41.png)

Wizard / Upload a source:
![image](https://user-images.githubusercontent.com/31689204/101786806-a89e8f80-3afe-11eb-9ba9-03ee4dcd061f.png)

Wizard / Finish:
![image](https://user-images.githubusercontent.com/31689204/101786900-c66bf480-3afe-11eb-85d4-c56709e7d20c.png)

**Comment by liekevdvoort** [comment]
![image](https://user-images.githubusercontent.com/49523639/113312397-88dbe300-930a-11eb-8c31-c7efff56b95f.png)

**Comment by liekevdvoort** [comment]
![image](https://user-images.githubusercontent.com/49523639/113314988-1c161800-930d-11eb-812f-e9c27a5eb6a7.png)
Mobile version is a bit strange try something with implementation
![image](https://user-images.githubusercontent.com/49523639/113315079-318b4200-930d-11eb-8879-b01ba874081c.png)
