### ISSUE TITLE
Redesign home page

### ISSUE THREAD

**Issue by devoncavis** [DigitalExcellence/dex-frontend#380]
**Is your feature request related to a problem? Please describe.**
The current home page does not give a clear view of what DeX is and what the user can expect from the platform.

**Describe the solution you'd like**
A home page redesign that gives users enough information to know what to expect and do with the platform. It should also offer enough options to kickstart the user into the rest of the website, with proper calls to action and tools to help them find what they're looking for.

**Additional context**
Returning (logged in) users who are already familiar with DeX could be given a more personalised experience. For example with less explanation about what DeX is and more recommended projects that might suit their personal interests.

**Comment by liekevdvoort** [comment]
V1 homepage small changes may be made later
![image](https://user-images.githubusercontent.com/49523639/113287930-85d2f980-92ee-11eb-9d23-ec878ee43dc8.png)

With this change implement a reusable footer with a prop for extra design elements as shown here
![image](https://user-images.githubusercontent.com/49523639/113287981-9be0ba00-92ee-11eb-8468-547814152d5c.png)
