### ISSUE TITLE
Refactor Friday - Update to Angular 11

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-frontend#385]
**Is your feature request related to a problem? Please describe.**
We're currently still using outdated Angular 9...

**Describe the solution you'd like**
Upgrade to Angular 10 and make use of some nice optimizations that might help with things like SEO

**Additional context**
https://www.angularminds.com/blog/article/comparison-between-angular-9-vs-angular-10.html

**Comment by rubenb994** [comment]
Lets update update to v11 instead of v10

**Comment by Brend-Smits** [comment]
Ah, right... thanks, @rubenb994!

**Comment by waltersajtos** [comment]
@RubenFricke I can pick this up but I think it's best to do this when no one is working on any branch on the front-end. I think we can implement it at the same time as #450
