### ISSUE TITLE
Color palette: New secondary color/footer color

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-frontend#398]
We need to research if the secondary color of DeX: #0156ff is a good fit for the project. 
The color is currently not being used. The secondary color could be used for the tags for instance.

**Comment by liekevdvoort** [comment]
![image](https://user-images.githubusercontent.com/49523639/105032287-e32d0d80-5a56-11eb-91ae-ced53974ce4a.png)

![ezgif-7-af040fc2a171](https://user-images.githubusercontent.com/49523639/105032255-dad4d280-5a56-11eb-940e-700aa353fdc1.gif)
