### ISSUE TITLE
Sign in SVG is gray

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-frontend#399]
**Describe the bug**
Sign in page includes the wrong .png

**To Reproduce**
1. Go to Sign-in page and check the login page

**Expected behavior**
Mobile image svg is default and should be changed like on the home page.
![99a55a15f86c4a996683bc1a2c520c81-png](https://user-images.githubusercontent.com/15904543/101952963-ce5c8f00-3bf9-11eb-841e-e2876a8e6655.jpg)

**Screenshots**
![6d3582a99b60dcd92c3018cdbee5c097-png](https://user-images.githubusercontent.com/15904543/101952936-c1d83680-3bf9-11eb-9ebf-de8f634af4a5.jpg)

**Production URL**
https://dex.software/account/login

**Additional context**

**Comment by waltersajtos** [comment]
@Brend-Smits is this still an issue? I can't reproduce it but no changes were made to that svg since 23/09/2020
