### ISSUE TITLE
Align project overview page title

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-frontend#400]
**Describe the bug**
The title from the project overview is not aligned with the rest of the page.

**To Reproduce**
1. Go to project overview
2. Open a modal by opening project details

**Expected behavior**
Align the project overview

**Screenshots**
![a338bdee311c3fb023a10b20a2220bb9-png (1)](https://user-images.githubusercontent.com/15904543/101953207-4034d880-3bfa-11eb-9920-f76b48166be7.jpg)

**Production URL**
https://dex.software/project/overview

**Comment by liekevdvoort** [comment]
It is actually only when you have clicked on a modal the bottom part becomes smaller or the top part becomes larger

**Comment by liekevdvoort** [comment]
![image](https://user-images.githubusercontent.com/49523639/102058631-10e7bc80-3df0-11eb-8485-52f52f66c5b2.png)

**Comment by Brend-Smits** [comment]
Related to #408
