### ISSUE TITLE
Search optimalization

### ISSUE THREAD

**Issue by niraymak** [DigitalExcellence/dex-frontend#403]
**Is your feature request related to a problem? Please describe.**
Currently Max and I are working on ElasticSearch. We want to use ElasticSearch to autocomplete and show results while typing in the search bar. 

**Describe the solution you'd like**
The frontend makes direct calls to the ElasticSearch.

**Comment by Brend-Smits** [comment]
Check out https://github.com/DigitalExcellence/dex-frontend/issues/196

**Comment by niraymak** [comment]
Max and I refactored this branch after all the changes that happened for the recommendation system.

![image](https://user-images.githubusercontent.com/44868678/113850038-56166c80-979a-11eb-97cf-512302859c2e.png)

It works with this backend branch.
https://github.com/DigitalExcellence/dex-backend/tree/feature/361-searchfuntionality

Anyone interested in showing the results underneath the search bar? @macfleury-2000 @liekevdvoort  @waltersajtos @RubenFricke

**Comment by niraymak** [comment]
Designs required.
