### ISSUE TITLE
Add tslint rule for relative imports

### ISSUE THREAD

**Issue by waltersajtos** [DigitalExcellence/dex-frontend#407]
**Is your feature request related to a problem? Please describe.**
I ran into this issue where my IDE automatically imports some module but it uses a relative path. 

**Describe the solution you'd like**
We should add a tslint rule for this that will throw an error if you use a relative path.

**Additional context**
There is a tslint contribution from microsoft called tslint-microsoft-contrib that includes a "no-relative-imports" rule.

**Comment by waltersajtos** [comment]
@Brend-Smits are you okay with it if I add a dev dependency for this?

**Comment by Brend-Smits** [comment]
Yes this can be added, please make sure it hasn't already been done though. Thanks for the suggestion @waltersajtos!
