### ISSUE TITLE
Design: New filter menu

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-frontend#413]
**Is your feature request related to a problem? Please describe.**
Current filter menu is lacking and should be redesigned

**Describe the solution you'd like**
Newly designed filter menu	

**Production URL**
Go to: https://dex.software/project/overview and on the left side you will view the filter menu that needs revamping

**Comment by liekevdvoort** [comment]
a few first versions feedback is welcome
![image](https://user-images.githubusercontent.com/49523639/104898291-bf47ca00-5979-11eb-8fab-20e45660fd20.png)
![image](https://user-images.githubusercontent.com/49523639/104898348-d38bc700-5979-11eb-8c2e-c4bccd26d4dd.png)
![image](https://user-images.githubusercontent.com/49523639/104898382-de465c00-5979-11eb-8b1e-8a933bd6c298.png)
![image](https://user-images.githubusercontent.com/49523639/104898454-f3bb8600-5979-11eb-8ef8-5a6a91262e84.png)
![image](https://user-images.githubusercontent.com/49523639/104898486-fcac5780-5979-11eb-8b02-49428a350fe2.png)
![image](https://user-images.githubusercontent.com/49523639/104898532-0cc43700-597a-11eb-8430-a26b4ccf937e.png)

**Comment by liekevdvoort** [comment]
@juliaslaats Yes thanks for the feedback will make those changes up in the next versions.

Yes then the searchbar can just be removed in the filtermenu I wanted to try if it worked in the filtermenu because that could save some space on the main part of the page. 

I did sorting options seperate because it already was that way i'm also fine with puting them in one input what does the rest think?

**Comment by Brend-Smits** [comment]
I personally like the second one the best. It's clean and simple. The search bar is still where it makes the most sense for now (at least in my opinion, this is very personal).

Great work!

**Comment by DaveyHurkmans** [comment]
I like the first one best, it still has a search bar and looks clean in general :)

**Comment by liekevdvoort** [comment]
![image](https://user-images.githubusercontent.com/49523639/105031690-f25f8b80-5a55-11eb-9d02-41245b62da6e.png)
![image](https://user-images.githubusercontent.com/49523639/105031729-01463e00-5a56-11eb-843a-d80a5b21f044.png)


![ezgif-7-af040fc2a171](https://user-images.githubusercontent.com/49523639/105032116-9ea17200-5a56-11eb-9ce2-605a8a3d0c2d.gif)

**Comment by juliaslaats** [comment]
We talked about this a little already, I think the designs look great like this.

I think the option with the changed footer color looks really sleek and gives DeX a little more character. It fixes the problem I mentioned with the drop shadow of the white footer on the white filter-bar.  It is a big change but it could also solve #398 and get us a secondary color that is actually usable 😄

**Comment by liekevdvoort** [comment]
After a design meeting the team decided that the white version should be implemented and we'll look later at the footer/secondary color issue.

The filtermenu now has lines in between the items if there is need for more space we can just get rid of them this is to give it a bit more body
