### ISSUE TITLE
Animation on 'liking' project

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-frontend#414]
**Is your feature request related to a problem? Please describe.**
Lack of animation of liking a project.

**Describe the solution you'd like**
Small 'heartbeat' animation when clicking on 'like'

**Comment by juliaslaats** [comment]
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/71012148/105167146-a1649b80-5b18-11eb-8ace-0ed254071e19.gif)

![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/71012148/105167280-cf49e000-5b18-11eb-9e33-94fbf27b612b.gif)
