### ISSUE TITLE
Different visuals for different browsers

### ISSUE THREAD

**Issue by RubenFricke** [DigitalExcellence/dex-frontend#422]
**Describe the bug**
Some visuals look different in FireFox, compared to Chrome or Edge. The design must be equalized as much as possible between the different browsers. 

**To Reproduce**
1. Most drop down icons have different visuals:
	Chrome: 
![image](https://user-images.githubusercontent.com/55654104/106130187-5a525800-6161-11eb-9ad4-7c92cf6e3d6f.png)
	FireFox:
![image](https://user-images.githubusercontent.com/55654104/106130287-735b0900-6161-11eb-9c6f-08632543085c.png)

2. I also noticed that the pagination icons are missing on FireFox:
	Chrome: 
![image](https://user-images.githubusercontent.com/55654104/106130436-9eddf380-6161-11eb-8b14-dee5a117f679.png)

	FireFox:
![image](https://user-images.githubusercontent.com/55654104/106130393-92f23180-6161-11eb-844a-d85a67b9c3f4.png)

**Expected behavior**
Walk through the website on different browsers and make sure the design is equalized (as much as possible) for the different browsers.
According to our test plan(https://docs.google.com/document/d/1aJjivrK0JK81uNJ0gxOPhkP6X6MKPHSTVCKI_SI_rys/edit), the following browsers should get tested:
Mozilla Firefox
Google Chrome
Microsoft Edge
Opera
Apple Safari

**Comment by RubenFricke** [comment]
Also, on firefox, your user name is in the center while on chrome everything is aligned.
![image](https://user-images.githubusercontent.com/55654104/111639485-98800580-87fb-11eb-8307-fb2e1673aca9.png)

**Comment by NealGeilen** [comment]
Different visuals fixed in #551
