### ISSUE TITLE
Like notification doesn't close on it's own. 

### ISSUE THREAD

**Issue by juliaslaats** [DigitalExcellence/dex-frontend#427]
**Describe the bug**
'Need to be logged in to like a project'-notification doesn't close on it's own. 

**To Reproduce**
1. Go to 'Project Overview'
2. Make sure you're not signed in
3. Click on 'Like'
4. See notification that doesn't disappear

**Expected behavior**
Notification goes away after a set time.

**Production URL**
https://dex.software/project/overview this is where you can see the problem. 

**Additional context**
Notifictation is not responsive on mobile, so not able to click it away on smaller screen.

**Comment by waltersajtos** [comment]
This should be fixed with https://github.com/DigitalExcellence/dex-frontend/pull/434, no? @RubenFricke

**Comment by RubenFricke** [comment]
> This should be fixed with #434, no? @RubenFricke

Good catch! Thanks :+1:
