### ISSUE TITLE
Highlighted project modal doesn't appear on homepage

### ISSUE THREAD

**Issue by RubenFricke** [DigitalExcellence/dex-frontend#436]
**Describe the bug**
When you click on a highlighted project on the homepage, and modal will popup and you will get navigated to the overview page. This last part should not happened. The modal should open on the homepage.

**To Reproduce**
1. Go to the homepage
2. Click on a highlighted project
3. A modal appears
4. Close the modal
5. You are on the project overview page

**Expected behavior**
The modal pop-up should open on the homepage instead of the overview page.

**Comment by waltersajtos** [comment]
I think it's better to block this until the new homepage is finished @RubenFricke

**Comment by NealGeilen** [comment]
This issue is no longer present
