### ISSUE TITLE
Alert does not go away

### ISSUE THREAD

**Issue by niraymak** [DigitalExcellence/dex-frontend#441]
**Describe the bug**
Alert modal does not go away when you try to update / delete a project that is not yours.

**To Reproduce**
1. Login
2. Try to delete or update a project that is not yours. 
3. Alert does not go away.

**Expected behavior**
Alert should go away after 5s.

**Screenshots**
![image](https://user-images.githubusercontent.com/44868678/112309875-2fd5d480-8ca4-11eb-84b9-3161cc3eb4ff.png)

**Production URL**
Example:
https://dex.software/project/details/118-kubernetes-workshop

**Comment by niraymak** [comment]
Looks like this was a problem earlier.

https://github.com/DigitalExcellence/dex-frontend/issues/392

**Comment by waltersajtos** [comment]
@niraymak can this be closed?
