### ISSUE TITLE
Active collaborators tab in detail modal

### ISSUE THREAD

**Issue by RubenFricke** [DigitalExcellence/dex-frontend#444]
**Describe the bug**
If I click on the project overview page on the collaborators from a project, it would make more sense if the collaborators tab is already opened instead of the description tab. 

**To Reproduce**
1. Go to the project overview page
2. Click on the ... Collaborators in a project
3. The project description tab is opened instead of the collaborators tab

**Expected behavior**
The collaborators tab is active.

**Comment by waltersajtos** [comment]
This was fixed in #447
