### ISSUE TITLE
Design and implement wizard pages for JsFiddle

### ISSUE THREAD

**Issue by RubenFricke** [DigitalExcellence/dex-frontend#468]
**Is your feature request related to a problem? Please describe.**
To import a project from JsFiddle you have to enter you username -> this will return all projects from that users and that user has to select which project he/she would like to import.

**Describe the solution you'd like**
A wizard page for entering your username should get designed and created.
A wizard page for an overview of all the projects from a user where he/she can select one project should get designed and created.

**Comment by waltersajtos** [comment]
Is this still relevent @RubenFricke? I thought the stakeholders didn't want this platform

**Comment by RubenFricke** [comment]
No, it's still a data source we would like to implement. The feedback we received is that we should **not** tease data sources that are not available yet. So JsFiddle is not available at this moment, and therefore we shouldn't show it yet on the data source page.

**Comment by liekevdvoort** [comment]
![image](https://user-images.githubusercontent.com/49523639/122540461-f5709f00-d028-11eb-928b-bedd8cc3ca2d.png)
The button with get projects can be removed if it isn't necesary for getting the data

![image](https://user-images.githubusercontent.com/49523639/122540504-ff929d80-d028-11eb-96ef-87c03f1be1d1.png)
