### ISSUE TITLE
Remove project icon does not work

### ISSUE THREAD

**Issue by RubenFricke** [DigitalExcellence/dex-frontend#482]
**Describe the bug**
Removing a project icon on the edit page does not work.

**To Reproduce**
1. Create a project with a project icon
2. Click on this project and navigate to the edit page
3. Remove the icon
4. Click on 'Edit Project'
5. Validate that the project icon has not been removed

**Expected behavior**
The project icon should get removed (maybe with a modal that asks for validation for removing the icon?)

**Screenshots**
![image](https://user-images.githubusercontent.com/55654104/117121884-84856880-ad95-11eb-8fa5-5c4b494fbe76.png)
This is the remove button I used that did not work.

**Comment by waltersajtos** [comment]
The UI has been changed quite a bit after this issue, right now there is no way to delete a project icon. In the wizard, there is no way to delete a project icon either. Might be a good idea to include that in this issue.
