### ISSUE TITLE
Filter menu integrated in unique url

### ISSUE THREAD

**Issue by RubenFricke** [DigitalExcellence/dex-frontend#493]
**Is your feature request related to a problem? Please describe.**
For the release for the AD students, a link should be able to get shared with a certain active filter bar. For example, a certain category already selected.

**Describe the solution you'd like**
The filter menu should be integrated into the URL. So certain states of the filter menu should be able to get shared.

**Comment by waltersajtos** [comment]
@RubenFricke is it okay if I do this in #475?

**Comment by RubenFricke** [comment]
> @RubenFricke is it okay if I do this in #475?

Sure 👍!
