### ISSUE TITLE
Homepage pop up like is not synced with the card

### ISSUE THREAD

**Issue by RubenFricke** [DigitalExcellence/dex-frontend#512]
**Describe the bug**
Liking a project from the homepage in a modal does not update the like amount in the card on the homepage.

**To Reproduce**
1. Go to the homepage
2. Make sure you are logged in and have recommended projects (if you don't have these, try liking some projects to get recommendations)
3. Open a project
4. Like the project in the modal
5. Validate that the card on the homepage is not updated with your like

**Expected behavior**
Liking in the modal should be synced with the card on the homepage

**Screenshots**
![image](https://user-images.githubusercontent.com/55654104/120791882-08697680-c535-11eb-9b97-3c9f65479637.png)
Here you can see that I liked the project in the popup, but the underlying card is not updated with my like.

**Additional context**
Look into the logic from the project overview. On the project overview, this is already working.

**Comment by juliaslaats** [comment]
@DaveBouman of @MeesvanStraten Lukt het jullie om die recommended projects te zien? Ik krijg ze met geen mogelijkheid online, ik heb al gechecked of het ergens anders mis gaat maar bij mij zijn er gewoon 0 recommended projects, zowel als ik met mijn eigen acc inlog als wanneer ik Bob Smith ben... Heb al vanalles geprobeerd te liken maar dat lijkt het niet te helpen :(

**Comment by MeesvanStraten** [comment]
@juliaslaats Local bedoel je? Misschien dat het namelijk local Elastic niet helemaal lekker werkt... Weet ik niet zeker nog. Maar zou ook kunnen dat Elastic niet instant is en er een tijdje over heen gaat voordat recommended projects verschijnen.

**Comment by juliaslaats** [comment]
@MeesvanStraten hmm okee, ik vrees dat het geen kwestie is van tijd, want dan zou het met Bob Smith inmiddels wel moeten werken... ik zal even zoeken naar een manier om lokaal Elastic te omzeilen en toch een paar projecten in die recommend te zetten. Als jij iets weet daarvoor hoor ik het graag 😄

**Comment by MeesvanStraten** [comment]
@juliaslaats  Heb ff wat gezocht. https://github.com/DigitalExcellence/dex-frontend/pull/498 Dit is de issue welke reccomended projects toevoegd. In de beschrijving staat waar de projecten moeten verschijnen. Dit is boven "What is DeX?".  Zie foto hieronder, dit is op production nadat ik wat projecten heb geliked.

![image](https://user-images.githubusercontent.com/41986758/132662550-4decc4bd-65af-49ba-99ba-35e79582ab85.png)
