### ISSUE TITLE
Discuss location of call to action

### ISSUE THREAD

**Issue by RubenFricke** [DigitalExcellence/dex-frontend#518]
**Is your feature request related to a problem? Please describe.**
Whenever the description is really long, you have to scroll for a while to see the call to action.

**Describe the solution you'd like**
We should discuss the location of the call to action and maybe relocate the location of the call to action(s)

**Additional context**
Comment from one of the sprint deliveries

**Comment by liekevdvoort** [comment]
![image](https://user-images.githubusercontent.com/49523639/122390378-35c11600-cf72-11eb-8833-750b40713e1b.png)
