### ISSUE TITLE
Keep our style consistent in (research)documents

### ISSUE THREAD

**Issue by RubenFricke** [DigitalExcellence/dex-frontend#522]
**Is your feature request related to a problem? Please describe.**
Lately, we have updated our homepage with an updated style. We also updated our presentation slides to keep this style consistent. 

While we have in our drive multiple research documents with different templates/styles. It would be nice to have the same style from the homepage and presentation slides also in our documents.

**Describe the solution you'd like**
Design / Create a template for documents that will be created in our drive according to the style from DeX.

**Comment by NealGeilen** [comment]
At the moment I have the following. 
I looked at the PowerPoint style used in presentations and the existing documentation for the contents.
Also, I maybe wanted to add a chapter page. This page would look like the chapter slide in the Powerpoint style. 

Would like to know what you think about this.

@MeesvanStraten 
@juliaslaats 
@1SvenHansen 

Title page
![image](https://user-images.githubusercontent.com/44571222/140054541-8da4ad71-23a7-42be-a3de-1585de278065.png)

Version history
![image](https://user-images.githubusercontent.com/44571222/140054774-1cd96a3d-a7b6-445b-ad9a-070f364b453b.png)

Table of contents page 
![image](https://user-images.githubusercontent.com/44571222/140054859-307f54df-72d0-4bc9-bf56-8f82fe7a5622.png)

**Comment by MeesvanStraten** [comment]
Looks good! Did you also set default fonts? like H1 etc?

**Comment by NealGeilen** [comment]
> Looks good! Did you also set default fonts? like H1 etc?

I have indeed set the default fonts for H and others to the same what is used with presentations

**Comment by MeesvanStraten** [comment]
Nice! For me this issue can be closed. you can wait for more feedback from others :)

**Comment by juliaslaats** [comment]
Looks good to me! Have you thought about how different headers with some body text would look in the document? Since I don't see a screenshot of that, maybe put some lorem ipsum into a little chapter mock-up for the visual? 

I also think a chapter-page, like you suggest, wouldn't really readability, so I wouldn't do that. You don't need the full-page focus like you do in a powerpoint-slide.

**Comment by NealGeilen** [comment]
> Looks good to me! Have you thought about how different headers with some body text would look in the document? Since I don't see a screenshot of that, maybe put some lorem ipsum into a little chapter mock-up for the visual?
> 
> I also think a chapter-page, like you suggest, wouldn't really readability, so I wouldn't do that. You don't need the full-page focus like you do in a powerpoint-slide.

![image](https://user-images.githubusercontent.com/44571222/140708671-8c601a65-4767-4339-b619-29e4fa4549df.png)
