### ISSUE TITLE
implement a comment system

### ISSUE THREAD

**Issue by niraymak** [DigitalExcellence/dex-frontend#532]
**Is your feature request related to a problem? Please describe.**
A team of Associate Degree students have been working on implementing a comment system on projects.

**Describe the solution you'd like**
Finalize the system:
TODO: 
frontend: 
- update and delete comment
- delete like comment
- styling
- improve refresh component

**Production URL**
See branch https://github.com/DigitalExcellence/dex-frontend/tree/feature/532-comment-system

**Additional context**

**Comment by 1SvenHansen** [comment]
@MeesvanStraten Would it be an idea for me to pick this one up upcoming week after the database constraints ticket?

**Comment by MeesvanStraten** [comment]
Let's look at it tomorrow, if we still need this and the state of the current implementation.
