### ISSUE TITLE
Searching on longer words yields no matching results

### ISSUE THREAD

**Issue by mmerel** [DigitalExcellence/dex-frontend#537]
If you search on projects, less characters yields more results while the text still matches...

**To Reproduce**
1. Go to https://dex.software/project/overview?sortOption=updated,desc&pagination=12&categories=%5B%5D&query=inzetma
4. No results

1. https://dex.software/project/overview?sortOption=updated,desc&pagination=12&categories=%5B%5D&query=inzet
2. Inzetmatcher result

**Expected behavior**
The project is still found

**Screenshots**
<img width="657" alt="bug-search" src="https://user-images.githubusercontent.com/5889445/123391275-1fcbda80-d59c-11eb-864f-5b08953d4512.png">

**Production URL**
?

**Additional context**
?

**Comment by RubenFricke** [comment]
Thanks for the input @mmerel . It seems to be a problem with the backend, so I relocated this issue to the backend. Thanks again, we will still try to pick this up this semester 😄!
