### ISSUE TITLE
Imgbot

### ISSUE THREAD

**Issue by niraymak** [DigitalExcellence/dex-frontend#540]
**Is your feature request related to a problem? Please describe.**
We would like imgbot to operate as a tool to compress images. This will increase the performance and improve the user experience of our frontend users. 

**Describe the solution you'd like**
https://github.com/marketplace/imgbot/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW4xNzQ5#pricing-and-setup

**Production URL**
Can this issue be linked to a relevant production URL? If so, please post the full link here, don't use hyperlinks.
If you can, post a short description around the url why it's relevant, this is good for SEO reasons.

**Additional context**

**Comment by RubenFricke** [comment]
Added to frontend and backend repository. This can be configured to update the selection of repositories that will be looked at.
