### ISSUE TITLE
As a manager of projects, I want to add my own categories so I can filter on them through a link to share with others

### ISSUE THREAD

**Issue by mmerel** [DigitalExcellence/dex-frontend#550]
**Describe the bug**
I want to have the possibility to filter on 'Digital Excellence', 'Research', 'HeliCop' projects.
https://dex.software/project/overview
https://dex.software/project/overview?query=&sortOption=updated,desc&pagination=12&categories=%5B4%5D

With categories "Ambition Digital Excellence", "Research", "HeliCop".

Also, I want to tag other project, that are not added by me, with those categories.

**Comment by niraymak** [comment]
What do you exactly mean by manager of projects? In our current implementation the user is the manager of his/her own projects and is also able to assign the predefined categories. These categories can be created, updated and deleted by the platform administrator.
Our plan is to also implement tags. Tags will be more specific than categories. 

The "Proftaak 2021 autumn" is a temporary category which we created as a temporary work around to do the FHICT Pilot this autumn.

We thought there was a issue for this, but there wasn't so we opened one.
https://github.com/DigitalExcellence/dex-backend/issues/485

I hope this matches your wishes. Please let us know if you have a different view on it.

**Comment by mmerel** [comment]
Hi Niray!

I don't think an extra role is needed; every user in the system should be able to add his/her 'sticky notes' to a project.

The goal that i have in mind, should support these use cases:

 - Possibility to 'cluster' projects based on the FHICT semester that collaborated: https://www.fontysictinnovationlab.nl/innovations-insight/#streams
 - To cluster them based on the research topic that funds them: https://fontys.nl/Over-Fontys/Fontys-Hogeschool-ICT/Onderzoek/Talks-1/Association-game.htm
 - To cluster them based on partners that collaborated https://www.partnersfontysict.nl/nl/overzicht-partners/

If you do it by category or tags is a technical decision, that maybe needs some analysis.

To use the platform in our FHICT organisation, this lacking functionality is however blocking :)

**Comment by MeesvanStraten** [comment]
Closing, tag system now supports this.
