### ISSUE TITLE
When creating a project in step 2 the description field is not big enough

### ISSUE THREAD

**Issue by DaveBouman** [DigitalExcellence/dex-frontend#562]
**Describe the bug**
In the second step of creating a new project. If the user has a big description the description overflows the page. This makes it hard to read the whole description while creating the project.

**To Reproduce**
1. Go to 'Add Project"
2. Go To step 2.
3. Insert text until the box overflows.

**Expected behavior**
In the right corner should be a way to increase the size of the box.

**Screenshots**
Current
![image](https://user-images.githubusercontent.com/49709450/132347172-577d7b84-2a18-4af0-aaed-1b2bc0aad4b6.png)

Expected
![image](https://user-images.githubusercontent.com/49709450/132347579-f0390122-2e8c-4470-91b3-4507abc07977.png)

**Production URL**
Can this issue be linked to a relevant production URL? If so, please post the full link here, don't use hyperlinks.
If you can, post a short description around the url why it's relevant, this is good for SEO reasons.

**Additional context**

**Comment by waltersajtos** [comment]
How do you expect this to work? Overflow outside of the wizard modal? We made it scrollable on purpose because overflowing looked really bad. Feel free to change it tho
