### ISSUE TITLE
Implementation Tag system for projects

### ISSUE THREAD

**Issue by DaveBouman** [DigitalExcellence/dex-frontend#597]
**Is your feature request related to a problem? Please describe.**
Currently we have categories implemented which are predefined by the adminstrators.
Our view on this is that categories are more of a global thing like IT. Tags are more specific like "Angular", "C#", "HTML" or and can be defined by our userbase.
It is important that these tags can and should be reused. Preferably our platform should not use different tags for the same thing like: "C#" and "C-sharp".

**Describe the solution you'd like**
Research a way to implement a tag system. Think about how this can be used to find projects. Think of a similar system as hashtags on Twitter.

**Additional context**
[There is also a backend issue for open](https://github.com/DigitalExcellence/dex-backend/issues/485)

**Comment by juliaslaats** [comment]
Hi guys! I made some designs on how to implement the tags. I would love some feedback!
We discussed making the tags pretty similar to the categories we have right now, so this is how I think it could look: 

**Overview page:**
![image](https://user-images.githubusercontent.com/71012148/144579740-db5bf3e1-5757-4fb4-ab15-38bcd94fab5f.png)
![image](https://user-images.githubusercontent.com/71012148/144579793-19c92f26-baaf-4143-acde-1f4a33fcce37.png)

**Detail page:**
![image](https://user-images.githubusercontent.com/71012148/144579967-97c2a502-6f9a-4e31-b118-bc7878d0a642.png)
![image](https://user-images.githubusercontent.com/71012148/144580008-ae234ef8-cf0c-4223-9f00-9f22f2e23601.png)

**Wizard Step: **
![image](https://user-images.githubusercontent.com/71012148/144580323-806b0eee-1cba-466a-b37d-562ca2227c6a.png)
![image](https://user-images.githubusercontent.com/71012148/144580373-d09f4a88-de1f-4695-908c-38dc8e916528.png)
![image](https://user-images.githubusercontent.com/71012148/144580417-631dd285-8fb8-4996-9bfc-79571d6bcb1c.png)


The other 'suggestion questions' could be these:
- What themes does your project have? (Glow, Education, Health)
- What workfield does your project relate to? (UX, Software, Technology, Infrastructure)
- Which competence level is the project? (Beginner, Intermediate, Expert)

Any other idea's to put into that list would be very welcome!

**Comment by MeesvanStraten** [comment]
Hey, Looks good!

Few questions:

1.  The first screenshot, on the left filter bar, would we just show the most popular tags? now it's only a few tags but for instance when we would have 1000 tags in the DB?

2. First screenshot, On the project cards, The "Label" and "Interactie" are example tags right? the +2 looks good :)

3. The wizard step 3 is a nice addition to help users add tags 👍 . Are you thinking of more questions? also when it's not programming related?

Great job, I think it looks clean 💯 .

**Comment by juliaslaats** [comment]
@MeesvanStraten 

> 1.  The first screenshot, on the left filter bar, would we just show the most popular tags? now it's only a few tags but for instance when we would have 1000 tags in the DB?

Yes, I think popular tags would be good and eventually maybe some personally recommended tags. In the first iteration it might just be a random selection of tags, depending on the data we have available. 

I agree that its definitely not a good idea to show all tags 😄

> 2. First screenshot, On the project cards, The "Label" and "Interactie" are example tags right? the +2 looks good :)

Yes, those are just slight poorly cosen example tags!


> Great job, I think it looks clean 💯 .

Thank you! 🤩

**Comment by juliaslaats** [comment]
Kleine update, begin in de code is gemaakt 👍  

![image](https://user-images.githubusercontent.com/71012148/145042243-8b81fd40-5546-457a-ab31-aac950cf01d8.png)
Het staat op [deze branch](https://github.com/DigitalExcellence/dex-frontend/tree/feature/597-tags-first-version)
