### ISSUE TITLE
Implement a "Modal" component

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-frontend#73]
In GitLab by @Brend-Smits on Apr 18, 2020, 19:50

I think it would be good to implement a re-usable modal component in the dex-frontend so that we can have uniform modals showing basic information or confirmation popups. This page can also be used to highlight projects as users only need to add some information like when they want the selected project to be highlighted (start and end date). Since these are only 2 fields, you don't want them to be redirected to a whole new page. A modal would be sufficient in this case.  
For more information, contact me.

**Comment by RensNooren** [comment]
Creating a separate issue for the design of the modal
