### ISSUE TITLE
Alert implementation

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-frontend#76]
In GitLab by @Brend-Smits on Apr 19, 2020, 13:17

If something goes wrong, we do not want to just show the exception to the user. We want them to see a nice error page.

**Comment by rubenb994** [comment]
Changed issue to use a toaster style for all alerts. Not only error alerts. Based on the alerts ngx-bootstrap has built in: https://valor-software.com/ngx-bootstrap/#/alerts
