### ISSUE TITLE
Error handling & interception

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-frontend#77]
In GitLab by @Brend-Smits on Apr 19, 2020, 13:19

If the API gives an error for whatever reason, we need to intercept it and handle it properly.

**Comment by Brend-Smits** [comment]
In the backend we show errors using the problem details standard. More information can be found in the issue https://github.com/DigitalExcellence/dex-backend/issues/80

**Comment by rubenb994** [comment]
What do we want to use the error handling for? To display messages to the user or just log it to the console? Or is there an other use for it?

**Comment by Brend-Smits** [comment]
> What do we want to use the error handling for? To display messages to the user or just log it to the console? Or is there an other use for it?

We have to intercept the error in the frontend and make decisions based on the error I think. This is open to discussion though. In some cases (like when saving an edit-project form, but getting a 500, you want to let the user know something went wrong in the backend and ask them to try again). 

Other errors we should maybe redirect them to an error page? 
Should we perhaps look into monitoring errors with tooling such as [Sentry](https://sentry.io/welcome/)

**Comment by rubenb994** [comment]
It is difficult to know though when the interceptor triggers what specific action caused the error to be triggered. For example I would not be able to differentiate between the following situations in which an error might get thrown: could not load the projects overview or could not post a new project.'

I think we should see this interceptor as a way to handle all errors equally and handle specific cases, where we for example need a redirect, within the components making the service calls.

I've looked into external monitoring tools, they all however require you to pay as soon as you want to have more than 1 user.

**Comment by Brend-Smits** [comment]
> It is difficult to know though when the interceptor triggers what specific action caused the error to be triggered. For example I would not be able to differentiate between the following situations in which an error might get thrown: could not load the projects overview or could not post a new project.'
> 
> I think we should see this interceptor as a way to handle all errors equally and handle specific cases, where we for example need a redirect, within the components making the service calls.

Okay so to confirm:
- One generic way to handle errors using the interceptor
- For specific cases we can specify it on the component level when calling the service if additional error handling is needed.

Please confirm/deny if I understood you correctly. If I did understand you correctly, I think this way of implementing this feature is perfectly fine! 

> I've looked into external monitoring tools, they all however require you to pay as soon as you want to have more than 1 user.

Sentry offers unlimited project en project members, with up to 500k events per month for students([Github educational package](https://education.github.com/pack)).  They also have [open source 'pricing' plans ](https://sentry.io/for/open-source/)which we might be able to use if the student plan is not sufficient. 
This would be a nice opportunity to test this error handling/tracking software, we can set it up to only track 404's in the frontend. In the backend, we could track the other errors.

**Comment by rubenb994** [comment]
Okay great, I will look into implementing Sentry. It seems like a cool way to log errors.

**Comment by Brend-Smits** [comment]
> Okay great, I will look into implementing Sentry. It seems like a cool way to log errors.

Sweet, do you want me to give you access to an account that we can use for DeX?
