### ISSUE TITLE
New design: illustrations

### ISSUE THREAD

**Issue by RensNooren** [DigitalExcellence/dex-frontend#97]
In sprint 2 we created a first version of a styleguide which shows a specific type of illustration. We need to replicate this illustration and create new / different versions for usage throughout DeX.

Possible illustrations could be:
- A computer
- A computer folder
- 404 page image
- Thank you screen
- Highlighted projects

The illustrations will be used to give a bit of flair to the interface.

**Comment by Brend-Smits** [comment]
@Eheijboer is this something you could work on in the coming weeks? 
It would be cool to use the DeX Rex next semester!

**Comment by Brend-Smits** [comment]
I recently found this website that we can use for some of these illustrations: https://undraw.co/illustrations
These are Open Source Illustrations with proper licenses that we can make use of.
